<a href="https://colab.research.google.com/github/izzatuliiman/data_science_w3/blob/main/Tutorial_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Q1


In [ ]:
import numpy as nump

arr = nump.array([[8, 5],
                [0, 9]])
print(arr)

[[8 5]
 [0 9]]


In [ ]:
#q2

In [ ]:
import numpy as nump
arr = nump.random.rand(3, 4)

print(arr)


[[0.29176945 0.08101905 0.23002078 0.68349515]
 [0.66930295 0.38095755 0.14953103 0.1006687 ]
 [0.00315006 0.78341967 0.0946642  0.32511333]]


In [ ]:
#q3


In [ ]:
import numpy as nump

ones_arr = nump.ones((3, 3))
print("array of ones:\n", ones_arr)

zeros_arr = nump.zeros((3, 3))
print("\narray of zeros:\n", zeros_arr)


array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#q4

In [ ]:
import numpy as nump

arr = nump.random.rand(6, 3)
print("6x3 array:\n", arr)

arr_T = arr.T
print("\ntranspose array (3x6):\n", arr_T)


6x3 array:
 [[0.30729036 0.81783947 0.22420548]
 [0.69772268 0.85376761 0.18122101]
 [0.13554271 0.63422656 0.4842833 ]
 [0.4714094  0.52030961 0.04129862]
 [0.24162177 0.84897381 0.31403734]
 [0.90062022 0.96977958 0.48078834]]

transpose array (3x6):
 [[0.30729036 0.69772268 0.13554271 0.4714094  0.24162177 0.90062022]
 [0.81783947 0.85376761 0.63422656 0.52030961 0.84897381 0.96977958]
 [0.22420548 0.18122101 0.4842833  0.04129862 0.31403734 0.48078834]]


In [ ]:
#q5

In [ ]:
import numpy as nump

n, p, m = 3, 4, 2

A = nump.random.rand(n, p)
B = nump.random.rand(p, m)

print("Matrix A (n x p):\n", A)
print("\nMatrix B (p x m):\n", B)

C = nump.dot(A, B)


print("\nDot product (A · B) → shape (n x m):\n", C)


Matrix A (n x p):
 [[0.77111482 0.45554864 0.54239478 0.98787335]
 [0.66168792 0.76232232 0.71644071 0.97376084]
 [0.20944024 0.7453191  0.28167464 0.83129428]]

Matrix B (p x m):
 [[0.43561215 0.65143306]
 [0.2527451  0.66916515]
 [0.87336943 0.75416302]
 [0.04349231 0.36681294]]

Dot product (A · B) → shape (n x m):
 [[0.96772059 1.57858579]
 [1.14898105 1.8386661 ]
 [0.56177139 1.15253597]]
